## **This file is all about Python Coding. All practices has been done via the course on https://www.codecademy.com/courses/data-processing-pandas/.**

In [ ]:
import pandas as pd

In [ ]:
#We normally create a dataframe by using the DataFrame function of Pandas

#Example 1

df1 = pd.DataFrame({
    'Row ID' : [1,2,3],
    'Name' : ['A','B','C'],
    'Role' : ['Engg','Artist','Gamer'],
    'Location' : ['X','Y','Z']
})

print(df1)

   Row ID Name    Role Location
0       1    A    Engg        X
1       2    B  Artist        Y
2       3    C   Gamer        Z

In [ ]:
#Another way of doing this is

df2 = pd.DataFrame([
    [1,'A','Engg','X'],
    [2,'B','Artist','Y'],
    [3,'C','Gamer','Z']
],columns=['Row ID','Name','Role','Location'])

print(df2)

   Row ID Name    Role Location
0       1    A    Engg        X
1       2    B  Artist        Y
2       3    C   Gamer        Z

In [ ]:
#Reading a file and then getting its top 10 rows plus its info

imbdMovieDf = pd.read_csv('IMDBMovies.csv')
imbdMovieDf.head(10)

   id                                       name   genre  year  imdb_rating
0   1                                     Avatar  action  2009          7.9
1   2                             Jurassic World  action  2015          7.3
2   3                               The Avengers  action  2012          8.1
3   4                            The Dark Knight  action  2008          9.0
4   5  Star Wars: Episode I - The Phantom Menace  action  1999          6.6
5   6                                  Star Wars  action  1977          8.7
6   7                    Avengers: Age of Ultron  action  2015          7.9
7   8                      The Dark Knight Rises  action  2012          8.5
8   9  Pirates of the Caribbean: Dead Mans Chest  action  2006          7.3
9  10                                 Iron Man 3  action  2013          7.3

In [ ]:
imbdMovieDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           220 non-null    int64
 1   name         220 non-null    object
 2   genre        220 non-null    object
 3   year         220 non-null    int64
 4   imdb_rating  220 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 8.7+ KB

In [ ]:
'''
If we want to get the entire information from a specific column
we can write either df[column_name] or df.column_name (this would work
in case the column follows all column naming standards)
'''
movie_name = imbdMovieDf['name']
print(movie_name)
print(type(movie_name)) #This would print the type as Series
print(type(imbdMovieDf)) #This would print the type as DataFrame

0                                         Avatar
1                                 Jurassic World
2                                   The Avengers
3                                The Dark Knight
4      Star Wars: Episode I - The Phantom Menace
                         ...
215                                     Hannibal
216                          Catch Me If You Can
217                                    Big Daddy
218                                        Se7en
219                                        Seven
Name: name, Length: 220, dtype: object
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [ ]:
'''
If we want to get information from multiple columns,
we would send a list of all column names
'''

movie_name_year = imbdMovieDf[['name','year']]
print(movie_name_year)
print(type(movie_name_year)) #This would print the type as DataFrame

                                          name  year
0                                       Avatar  2009
1                               Jurassic World  2015
2                                 The Avengers  2012
3                              The Dark Knight  2008
4    Star Wars: Episode I - The Phantom Menace  1999
..                                         ...   ...
215                                   Hannibal  2001
216                        Catch Me If You Can  2002
217                                  Big Daddy  1999
218                                      Se7en  1995
219                                      Seven  1979

[220 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#If we want to get a information about a specific row, we use the iloc command

imbdMovieDf.head(10)

   id                                       name   genre  year  imdb_rating
0   1                                     Avatar  action  2009          7.9
1   2                             Jurassic World  action  2015          7.3
2   3                               The Avengers  action  2012          8.1
3   4                            The Dark Knight  action  2008          9.0
4   5  Star Wars: Episode I - The Phantom Menace  action  1999          6.6
5   6                                  Star Wars  action  1977          8.7
6   7                    Avengers: Age of Ultron  action  2015          7.9
7   8                      The Dark Knight Rises  action  2012          8.5
8   9  Pirates of the Caribbean: Dead Mans Chest  action  2006          7.3
9  10                                 Iron Man 3  action  2013          7.3

In [ ]:
row3 = imbdMovieDf.iloc[3]
print(row3)
print(type(row3))

id                           4
name           The Dark Knight
genre                   action
year                      2008
imdb_rating                9.0
Name: 3, dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
#If we want to print multiple rows, we can pass the series of the row numbers
#dataFrame.iloc[10:] -> 10 to the end of dataframe
#dataFrame.iloc[10:15] -> 10 to 14 of dataframe
#dataFrame.iloc[-5:] -> 5 rows from the end of dataframe

print(imbdMovieDf.iloc[-10:])

      id                 name  genre  year  imdb_rating
210  211     A Beautiful Mind  drama  2001          8.2
211  212             The Help  drama  2011          8.1
212  213     3 Men and a Baby  drama  1987          5.9
213  214            Gone Girl  drama  2014          8.2
214  215      Kung Fu Panda 2  drama  2011          7.3
215  216             Hannibal  drama  2001          6.7
216  217  Catch Me If You Can  drama  2002          8.0
217  218            Big Daddy  drama  1999          6.4
218  219                Se7en  drama  1995          8.6
219  220                Seven  drama  1979          6.1

In [ ]:
#Lets say if we want to print the information for the movie released in the year 2008

movie_2008 = imbdMovieDf[imbdMovieDf['year'] == 2008]
print(movie_2008)
print(type(movie_2008)) #This would also retuen type as dataframe

      id                                               name    genre  year  \
3      4                                    The Dark Knight   action  2008
20    21                                           Iron Man   action  2008
21    22  Indiana Jones and the Kingdom of the Crystal S...   action  2008
84    85                                      Kung Fu Panda   comedy  2008
126  127                                        Cloverfield   horror  2008
158  159                                           Twilight  romance  2008
175  176                                   Sex and the City  romance  2008
183  184                                         Mamma Mia!  romance  2008
185  186                                        Marley & Me  romance  2008
187  188                                Slumdog Millionaire  romance  2008

     imdb_rating
3            9.0
20           7.9
21           6.2
84           7.6
126          7.1
158          5.2
175          5.5
183          6.4
185          7.1
187          8.0
<class 'pandas.core.frame.DataFrame'>

In [ ]:
#Lets say if we want to print the information for the movie released in the year 2008 or year 2009

movie_2008_2009 = imbdMovieDf[(imbdMovieDf['year'] == 2008) | (imbdMovieDf['year'] == 2009)]
print(movie_2008_2009)

#This can be achieved via another command - isin()

movie_2008_2009_withIsIN = imbdMovieDf[imbdMovieDf['year'].isin(
    [2008,2009]
)]

print(movie_2008_2009_withIsIN)

      id                                               name    genre  year  \
0      1                                             Avatar   action  2009
3      4                                    The Dark Knight   action  2008
11    12                Transformers: Revenge of the Fallen   action  2009
20    21                                           Iron Man   action  2008
21    22  Indiana Jones and the Kingdom of the Crystal S...   action  2008
37    38                                          Star Trek   action  2009
58    59                                                 Up   comedy  2009
62    63                                       The Hangover   comedy  2009
78    79            Alvin and the Chipmunks: The Squeakquel   comedy  2009
84    85                                      Kung Fu Panda   comedy  2008
93    94                                Monsters vs. Aliens   comedy  2009
95    96                     Ice Age: Dawn of the Dinosaurs   comedy  2009
126  127                                        Cloverfield   horror  2008
129  130                                         Zombieland   horror  2009
140  141                              The Final Destination   horror  2009
144  145                                    Friday the 13th   horror  2009
149  150                        The Twilight Saga: New Moon  romance  2009
158  159                                           Twilight  romance  2008
172  173                                       The Proposal  romance  2009
175  176                                   Sex and the City  romance  2008
183  184                                         Mamma Mia!  romance  2008
185  186                                        Marley & Me  romance  2008
187  188                                Slumdog Millionaire  romance  2008
195  196                                     The Blind Side    drama  2009

     imdb_rating
0            7.9
3            9.0
11           6.0
20           7.9
21           6.2
37           8.0
58           8.3
62           7.8
78           4.4
84           7.6
93           6.6
95           7.0
126          7.1
129          7.7
140          5.2
144          5.6
149          4.6
158          5.2
172          6.7
175          5.5
183          6.4
185          7.1
187          8.0
195          7.7
      id                                               name    genre  year  \
0      1                                             Avatar   action  2009
3      4                                    The Dark Knight   action  2008
11    12                Transformers: Revenge of the Fallen   action  2009
20    21                                           Iron Man   action  2008
21    22  Indiana Jones and the Kingdom of the Crystal S...   action  2008
37    38                                          Star Trek   action  2009
58    59                                                 Up   comedy  2009
62    63                                       The Hangover   comedy  2009
78    79            Alvin and the Chipmunks: The Squeakquel   comedy  2009
84    85                                      Kung Fu Panda   comedy  2008
93    94                                Monsters vs. Aliens   comedy  2009
95    96                     Ice Age: Dawn of the Dinosaurs   comedy  2009
126  127                                        Cloverfield   horror  2008
129  130                                         Zombieland   horror  2009
140  141                              The Final Destination   horror  2009
144  145                                    Friday the 13th   horror  2009
149  150                        The Twilight Saga: New Moon  romance  2009
158  159                                           Twilight  romance  2008
172  173                                       The Proposal  romance  2009
175  176                                   Sex and the City  romance  2008
183  184                                         Mamma Mia!  romance  2008
185  186                                        Marley & Me  romance  2008
187  188                                Slumdog Millionaire  romance  2008
195  196                                     The Blind Side    drama  2009

     imdb_rating
0            7.9
3            9.0
11           6.0
20           7.9
21           6.2
37           8.0
58           8.3
62           7.8
78           4.4
84           7.6
93           6.6
95           7.0
126          7.1
129          7.7
140          5.2
144          5.6
149          4.6
158          5.2
172          6.7
175          5.5
183          6.4
185          7.1
187          8.0
195          7.7

In [ ]:
#When we want to reset the index and also have re-ordering done, we use reset_index()
df = pd.DataFrame([
  ['January', 100, 100, 23, 100],
  ['February', 51, 45, 145, 45],
  ['March', 81, 96, 65, 96],
  ['April', 80, 80, 54, 180],
  ['May', 51, 54, 54, 154],
  ['June', 112, 109, 79, 129]],
  columns=['month', 'clinic_east',
           'clinic_north', 'clinic_south',
           'clinic_west']
)

df2 = df.loc[[1, 3, 5]]
print(df2)

df3 = df2.reset_index()
print(df3)

df2.reset_index(inplace= True ,drop = True)
print(df2)

      month  clinic_east  clinic_north  clinic_south  clinic_west
1  February           51            45           145           45
3     April           80            80            54          180
5      June          112           109            79          129
   index     month  clinic_east  clinic_north  clinic_south  clinic_west
0      1  February           51            45           145           45
1      3     April           80            80            54          180
2      5      June          112           109            79          129
      month  clinic_east  clinic_north  clinic_south  clinic_west
0  February           51            45           145           45
1     April           80            80            54          180
2      June          112           109            79          129

In [ ]:
#Exercise 1: Analysis of the ShoeFly database

orders = pd.read_csv('shoefly.csv')

#Inspect the first 5 lines of data
print(orders.head())

#Your marketing department wants to send out an email blast to everyone who ordered shoes!

emails = orders['email']
print(emails)

#Frances Palmer claims that her order was wrong. What did Frances Palmer order?

frances_palmer = orders[(orders['first_name'] == 'Frances') | (orders['last_name'] == 'Palmer')]
print(frances_palmer)

#We need some customer reviews for our comfortable shoes. Select all orders for shoe_type: clogs, boots, and ballet flats and save them to the variable comfy_shoes.
comfy_shoes = orders[orders['shoe_type'].isin(['clogs','boots','ballet flats'])]
print(comfy_shoes)

      id first_name last_name                         email     shoe_type  \
0  54791    Rebecca   Lindsay  RebeccaLindsay57@hotmail.com         clogs
1  53450      Emily     Joyce        EmilyJoyce25@gmail.com  ballet flats
2  91987      Joyce    Waller        Joyce.Waller@gmail.com       sandals
3  14437     Justin  Erickson   Justin.Erickson@outlook.com         clogs
4  79357     Andrew     Banks              AB4318@gmail.com         boots

  shoe_material shoe_color
0  faux-leather      black
1  faux-leather       navy
2        fabric      black
3  faux-leather        red
4       leather      brown
0     RebeccaLindsay57@hotmail.com
1           EmilyJoyce25@gmail.com
2           Joyce.Waller@gmail.com
3      Justin.Erickson@outlook.com
4                 AB4318@gmail.com
5           JulieMarsh59@gmail.com
6                 TJ5470@gmail.com
7           Janice.Hicks@gmail.com
8        GabrielPorter24@gmail.com
9        FrancesPalmer50@gmail.com
10         JessicaHale25@gmail.com
11      LawrenceParker44@gmail.com
12         SusanDennis58@gmail.com
13                DO2680@gmail.com
14       Rebecca.Charles@gmail.com
15              JC2072@hotmail.com
16              VS4753@outlook.com
17          RoyTillman20@gmail.com
18       Thomas.Roberson@gmail.com
19         ANewton1977@outlook.com
Name: email, dtype: object
      id first_name last_name                      email shoe_type  \
9  62083    Frances    Palmer  FrancesPalmer50@gmail.com    wedges

  shoe_material shoe_color
9       leather      white
       id first_name   last_name                         email     shoe_type  \
0   54791    Rebecca     Lindsay  RebeccaLindsay57@hotmail.com         clogs
1   53450      Emily       Joyce        EmilyJoyce25@gmail.com  ballet flats
3   14437     Justin    Erickson   Justin.Erickson@outlook.com         clogs
4   79357     Andrew       Banks              AB4318@gmail.com         boots
6   20487     Thomas      Jensen              TJ5470@gmail.com         clogs
7   76971     Janice       Hicks        Janice.Hicks@gmail.com         clogs
8   21586    Gabriel      Porter     GabrielPorter24@gmail.com         clogs
10  91629    Jessica        Hale       JessicaHale25@gmail.com         clogs
12  45832      Susan      Dennis       SusanDennis58@gmail.com  ballet flats
14  73431    Rebecca     Charles     Rebecca.Charles@gmail.com         boots
16  39888    Vincent  Stephenson            VS4753@outlook.com         boots
17  35961        Roy     Tillman        RoyTillman20@gmail.com         boots

   shoe_material shoe_color
0   faux-leather      black
1   faux-leather       navy
3   faux-leather        red
4        leather      brown
6         fabric       navy
7   faux-leather       navy
8        leather      brown
10       leather        red
12        fabric      white
14  faux-leather      white
16       leather      black
17       leather      white

In [ ]:
#Part 2: Adding New Columns to the Dataframe, the new column has to have data for all the rows

df4 = pd.DataFrame([
    [1,'A',23],
    [2,'B',33]
], columns = ['Sr No','Name','Age'])

df4

   Sr No Name  Age
0      1    A   23
1      2    B   33

In [ ]:
df4['Job'] = ['IT','Artist']
df4

   Sr No Name  Age     Job
0      1    A   23      IT
1      2    B   33  Artist

In [ ]:
#What if we have a column that has Same value for all rows.

df4['Currently Employed'] = 'Yes'
df4

   Sr No Name  Age     Job Currently Employed
0      1    A   23      IT                Yes
1      2    B   33  Artist                Yes

In [ ]:
#What if you want a column that does some calculation based on some other columns of the dataset

df5 = pd.DataFrame([
  [1, '3 inch screw', 0.5, 0.75],
  [2, '2 inch nail', 0.10, 0.25],
  [3, 'hammer', 3.00, 5.50],
  [4, 'screwdriver', 2.50, 3.00]
],
  columns=['Product ID', 'Description', 'Cost to Manufacture', 'Price']
)

df5['Margin'] = df5['Price'] - df5['Cost to Manufacture']
df5

   Product ID   Description  Cost to Manufacture  Price  Margin
0           1  3 inch screw                  0.5   0.75    0.25
1           2   2 inch nail                  0.1   0.25    0.15
2           3        hammer                  3.0   5.50    2.50
3           4   screwdriver                  2.5   3.00    0.50

In [ ]:
#Lets say you want to apply lower case and upper case functionality to some columns to your dataframe.

df4.head()

   Sr No Name  Age     Job Currently Employed
0      1    A   23      IT                Yes
1      2    B   33  Artist                Yes

In [ ]:
df4['Lower_Case_Name'] = df4['Name'].apply(str.lower)
df4['Job'] = df4['Job'].apply(str.upper)
df4

   Sr No Name  Age     Job Currently Employed Lower_Case_Name
0      1    A   23      IT                Yes               a
1      2    B   33  ARTIST                Yes               b

In [ ]:
#Some practice on Lambda function

lambdaFunction = lambda x : (x * 2) + 3
print(f'The value for function 1:{lambdaFunction(5)}')

lambdafunction2 = lambda x: x.lower()
print(f'The value for function 2:{lambdafunction2('LOWER TEXT')}')

#Create a lambda function mylambda that returns the first and last letters of a string, assuming the string is at least 2 characters long.

lambdafunction3 = lambda x : x[0] + x[-1]
print(f'The value of function 3:{lambdafunction3('This is Pandas Practice')}')

#More Complex function

def myfunction(x):
  if x > 40:
    return 40 + (x - 40) * 1.50
  else:
    return x

#The above can be written as

lambdafunction4 = lambda x: 40 + (x - 40) * 1.50 if x > 40 else x
print(f'The value for function 4:{lambdafunction4(5)}')
print(f'The value for function 4:{lambdafunction4(50)}')

#The syntax is lambda x: TRUE STATEMENT - IF CONDITION - ELSE CONDITION

#You are managing the webpage of a somewhat violent video game and you want to check that each user’s age is 13 or greater when they visit the site.
#Write a lambda function that takes an inputted age and either returns Welcome to BattleCity! if the user is 13 or older or You must be 13 or older
#if they are younger than 13. Your lambda function should be called mylambda.

mylambda = lambda x : 'Welcome to BattleCity!' if x >= 13 else 'You must be 13 or older'
print(mylambda(int(input('Enter the age:'))))

The value for function 1:13
The value for function 2:lower text
The value of function 3:Te
The value for function 4:5
The value for function 4:55.0
Enter the age:13
Welcome to BattleCity!

In [ ]:
#Applying lambda function on DataFrames

employeesDf = pd.read_csv('employees.csv')
employeesDf.head()

      id               name  hourly_wage  hours_worked
0  10310      Lauren Durham           19            43
1  18656      Grace Sellers           17            40
2  61254  Shirley Rasmussen           16            30
3  16886        Brian Rojas           18            47
4  89010    Samantha Mosley           11            38

In [ ]:
#Create a lambda function get_last_name which takes a string with someone’s first and last name (i.e., John Smith), and returns just the last name (i.e., Smith).

get_last_name = lambda x : x.split(' ')[-1]
employeesDf['last name'] = employeesDf['name'].apply(get_last_name)
employeesDf.head()

      id               name  hourly_wage  hours_worked  last name
0  10310      Lauren Durham           19            43     Durham
1  18656      Grace Sellers           17            40    Sellers
2  61254  Shirley Rasmussen           16            30  Rasmussen
3  16886        Brian Rojas           18            47      Rojas
4  89010    Samantha Mosley           11            38     Mosley

In [ ]:
'''
If an employee worked for more than 40 hours, she needs to be paid overtime (1.5 times the normal hourly wage).
For instance, if an employee worked for 43 hours and made $10/hour, she would receive $400 for the first 40 hours that she worked,
and an additional $45 for the 3 hours of overtime, for a total for $445.
Create a lambda function total_earned that accepts an input row with keys hours_worked and hourly_wage and
uses an if statement to calculate the total wages earned.
'''


total_earned = lambda row : (row.hourly_wage * 40) + ((row.hourly_wage * 1.5) * (row.hours_worked - 40)) if row.hours_worked > 40 else row.hours_worked * row.hourly_wage

employeesDf['total_earned'] = employeesDf.apply(total_earned, axis=1)
employeesDf.head(10)

,id,name,hourly_wage,hours_worked,last name,total_earned
0,10310,Lauren Durham,19,43,Durham,845.5
1,18656,Grace Sellers,17,40,Sellers,680.0
2,61254,Shirley Rasmussen,16,30,Rasmussen,480.0
3,16886,Brian Rojas,18,47,Rojas,909.0
4,89010,Samantha Mosley,11,38,Mosley,418.0
5,87246,Louis Guzman,14,39,Guzman,546.0
6,20578,Denise Mcclure,15,40,Mcclure,600.0
7,12869,James Raymond,15,32,Raymond,480.0
8,53461,Noah Collier,18,35,Collier,630.0
9,14746,Donna Frederick,20,41,Frederick,830.0

In [ ]:
imbdMovieDf.head()

   id                                       name   genre  year  imdb_rating
0   1                                     Avatar  action  2009          7.9
1   2                             Jurassic World  action  2015          7.3
2   3                               The Avengers  action  2012          8.1
3   4                            The Dark Knight  action  2008          9.0
4   5  Star Wars: Episode I - The Phantom Menace  action  1999          6.6

In [ ]:
#Renaming the columns is done with the below

imbdMovieDf.columns = ['ID','Title','Genre','Year','IMDb_Rating']
imbdMovieDf.head()

   ID                                      Title   Genre  Year  IMDb_Rating
0   1                                     Avatar  action  2009          7.9
1   2                             Jurassic World  action  2015          7.3
2   3                               The Avengers  action  2012          8.1
3   4                            The Dark Knight  action  2008          9.0
4   5  Star Wars: Episode I - The Phantom Menace  action  1999          6.6

In [ ]:
#Lets imagine you want to change the Column names from ID to Id and Title to Movie Name

imbdMovieDf.rename(columns={
    'ID' : 'Id',
    'Title' : 'Movie Name'
}, inplace=True)
imbdMovieDf.head()

   Id                                 Movie Name   Genre  Year  IMDb_Rating
0   1                                     Avatar  action  2009          7.9
1   2                             Jurassic World  action  2015          7.3
2   3                               The Avengers  action  2012          8.1
3   4                            The Dark Knight  action  2008          9.0
4   5  Star Wars: Episode I - The Phantom Menace  action  1999          6.6

In [ ]:
orders = pd.read_csv('shoeflyorderlist.csv')
orders.head()

#Once more, you’ll be the data analyst for ShoeFly.com, a fictional online shoe store.
#More messy order data has been loaded into the variable orders. Examine the first 5 rows of the data using print and .head().

shoe_source = lambda row : 'vegan' if (row.shoe_material != 'leather') else 'animal'
orders['shoe_source'] = orders.apply(shoe_source,axis=1)

#Our marketing department wants to send out an email to each customer. Using the columns last_name and gender create a column called salutation which contains Dear Mr. <last_name> for men and Dear Ms. <last_name> for women.

salutation = lambda row : 'Dear Mr. '+row.last_name if row.gender == 'male' else 'Dear Ms. '+row.last_name
orders['salutation'] = orders.apply(salutation,axis=1)
print(orders.head(10))

      id first_name last_name  gender                         email  \
0  54791    Rebecca   Lindsay  female  RebeccaLindsay57@hotmail.com
1  53450      Emily     Joyce  female        EmilyJoyce25@gmail.com
2  91987      Joyce    Waller  female        Joyce.Waller@gmail.com
3  14437     Justin  Erickson    male   Justin.Erickson@outlook.com
4  79357     Andrew     Banks    male              AB4318@gmail.com
5  52386      Julie     Marsh  female        JulieMarsh59@gmail.com
6  20487     Thomas    Jensen    male              TJ5470@gmail.com
7  76971     Janice     Hicks  female        Janice.Hicks@gmail.com
8  21586    Gabriel    Porter    male     GabrielPorter24@gmail.com
9  62083    Frances    Palmer  female     FrancesPalmer50@gmail.com

      shoe_type shoe_material shoe_color shoe_source         salutation
0         clogs  faux-leather      black       vegan   Dear Ms. Lindsay
1  ballet flats  faux-leather       navy       vegan     Dear Ms. Joyce
2       sandles        fabric      black       vegan    Dear Ms. Waller
3         clogs  faux-leather        red       vegan  Dear Mr. Erickson
4         boots       leather      brown      animal     Dear Mr. Banks
5       sandles        fabric      black       vegan     Dear Ms. Marsh
6         clogs        fabric       navy       vegan    Dear Mr. Jensen
7         clogs  faux-leather       navy       vegan     Dear Ms. Hicks
8         clogs       leather      brown      animal    Dear Mr. Porter
9        wedges       leather      white      animal    Dear Ms. Palmer

**Final Project of the module 1:**

In [ ]:
import pandas as pd

#Data for all of the locations of Petal Power is in the file inventory.csv. Load the data into a DataFrame called inventory.
inventory = pd.read_csv('inventory.csv')

#Inspect the first 10 rows of inventory.
print(inventory.head(10))

#The first 10 rows represent data from your Staten Island location. Select these rows and save them to staten_island.
staten_island = inventory.iloc[:10]
print(staten_island)

#A customer just emailed you asking what products are sold at your Staten Island location. Select the column product_description from staten_island and save it to the variable product_request.
find_product_for_staten = lambda row : row.product_description \
if row.location == 'Staten Island' else None
product_request = inventory.apply(find_product_for_staten, axis=1)
print(product_request)

#Another way
#product_request = inventory[inventory.location == 'Staten Island'].product_description

#Another customer emails to ask what types of seeds are sold at the Brooklyn location.
#Select all rows where location is equal to Brooklyn and product_type is equal to seeds and save them to the variable seed_request.

seed_request = inventory[(inventory['location'] == 'Brooklyn') & (inventory['product_type'] == 'seeds')]

#Add a column to inventory called in_stock which is True if quantity is greater than 0 and False if quantity equals 0.

in_stock = lambda x: 'True' if x > 0 else False
inventory['in_stock'] = inventory['quantity'].apply(in_stock)

#Petal Power wants to know how valuable their current inventory is.
#Create a column called total_value that is equal to price multiplied by quantity.

inventory['total_value'] = inventory['quantity'] * inventory['price']

#The Marketing department wants a complete description of each product for their catalog.

combine_lambda = lambda row: \
    '{} - {}'.format(row.product_type, \
                     row.product_description)

inventory['full_description'] = inventory.apply(combine_lambda,axis=1)

        location  product_type         product_description  quantity  price
0  Staten Island         seeds                       daisy         4   6.99
1  Staten Island         seeds                  calla lily        46  19.99
2  Staten Island         seeds                      tomato        85  13.99
3  Staten Island  garden tools                        rake         4  13.99
4  Staten Island  garden tools                 wheelbarrow         0  89.99
5  Staten Island  garden tools                       spade        93  19.99
6  Staten Island  pest_control               insect killer        74  12.99
7  Staten Island  pest_control                 weed killer         8  23.99
8  Staten Island       planter  20 inch terracotta planter         0  17.99
9  Staten Island       planter      8 inch plastic planter        53   3.99
        location  product_type         product_description  quantity  price
0  Staten Island         seeds                       daisy         4   6.99
1  Staten Island         seeds                  calla lily        46  19.99
2  Staten Island         seeds                      tomato        85  13.99
3  Staten Island  garden tools                        rake         4  13.99
4  Staten Island  garden tools                 wheelbarrow         0  89.99
5  Staten Island  garden tools                       spade        93  19.99
6  Staten Island  pest_control               insect killer        74  12.99
7  Staten Island  pest_control                 weed killer         8  23.99
8  Staten Island       planter  20 inch terracotta planter         0  17.99
9  Staten Island       planter      8 inch plastic planter        53   3.99
0                          daisy
1                     calla lily
2                         tomato
3                           rake
4                    wheelbarrow
5                          spade
6                  insect killer
7                    weed killer
8     20 inch terracotta planter
9         8 inch plastic planter
10                          None
11                          None
12                          None
13                          None
14                          None
15                          None
16                          None
17                          None
18                          None
19                          None
20                          None
21                          None
22                          None
23                          None
24                          None
25                          None
26                          None
27                          None
28                          None
dtype: object

In [ ]:
print(inventory.head(10))

        location  product_type         product_description  quantity  price  \
0  Staten Island         seeds                       daisy         4   6.99
1  Staten Island         seeds                  calla lily        46  19.99
2  Staten Island         seeds                      tomato        85  13.99
3  Staten Island  garden tools                        rake         4  13.99
4  Staten Island  garden tools                 wheelbarrow         0  89.99
5  Staten Island  garden tools                       spade        93  19.99
6  Staten Island  pest_control               insect killer        74  12.99
7  Staten Island  pest_control                 weed killer         8  23.99
8  Staten Island       planter  20 inch terracotta planter         0  17.99
9  Staten Island       planter      8 inch plastic planter        53   3.99

  in_stock  total_value                      full_description
0     True        27.96                         seeds - daisy
1     True       919.54                    seeds - calla lily
2     True      1189.15                        seeds - tomato
3     True        55.96                   garden tools - rake
4    False         0.00            garden tools - wheelbarrow
5     True      1859.07                  garden tools - spade
6     True       961.26          pest_control - insect killer
7     True       191.92            pest_control - weed killer
8    False         0.00  planter - 20 inch terracotta planter
9     True       211.47      planter - 8 inch plastic planter

# **Aggregation in Pandas**

In [ ]:
orders = pd.read_csv('orders.csv')
print(orders.head(10))
print(orders.info())
most_expensive = orders['price'].max() #This would print the max value of price in the entire column [min would print the min value]
print(most_expensive)
num_colors = orders['shoe_color'].nunique() #This would print the count of unique values in the column
print(num_colors)
unique_colors = orders['shoe_color'].unique() #This would print all the unique values in that column
print(unique_colors)
sum_prices = orders['price'].sum() #This would do the sum of all the values in the column
print(sum_prices)
count_first_name = orders['first_name'].count() #This would print the count of entries in the column
print(count_first_name)

      id first_name    last_name                         email     shoe_type  \
0  41874       Kyle         Peck          KylePeck71@gmail.com  ballet flats
1  31349  Elizabeth    Velazquez      EVelazquez1971@gmail.com         boots
2  43416      Keith     Saunders              KS4047@gmail.com       sandals
3  56054       Ryan      Sweeney     RyanSweeney14@outlook.com       sandals
4  77402      Donna  Blankenship              DB3807@gmail.com     stilettos
5  97148     Albert       Dillon       Albert.Dillon@gmail.com        wedges
6  19998     Judith       Hewitt      JudithHewitt98@gmail.com     stilettos
7  83290      Kayla       Hardin        Kayla.Hardin@gmail.com     stilettos
8  77867     Steven  Blankenship  Steven.Blankenship@gmail.com        wedges
9  54885      Carol   Mclaughlin              CM3415@gmail.com  ballet flats

  shoe_material shoe_color  price
0  faux-leather      black  385.0
1        fabric      brown  388.0
2       leather       navy  346.0
3        fabric      brown  344.0
4        fabric      brown  289.0
5        fabric      brown  266.0
6       leather      black  395.0
7       leather      white  241.0
8       leather       navy  266.0
9  faux-leather      brown  440.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             99 non-null     int64
 1   first_name     99 non-null     object
 2   last_name      99 non-null     object
 3   email          99 non-null     object
 4   shoe_type      99 non-null     object
 5   shoe_material  99 non-null     object
 6   shoe_color     99 non-null     object
 7   price          98 non-null     float64
dtypes: float64(1), int64(1), object(6)
memory usage: 6.3+ KB
None
493.0
5
['black' 'brown' 'navy' 'white' 'red']
28335.0
99

In [ ]:
#Finance department wants to know the most expensive shoe for each shoe_type (i.e., the most expensive boot, the most expensive ballet flat, etc.).

pricey_shoe = orders.groupby('shoe_type').price.max() #Syntax would be df.groupby('column1').column2.measurement()
print(pricey_shoe)

shoe_type
ballet flats    481.0
boots           478.0
clogs           493.0
sandals         456.0
stilettos       487.0
wedges          461.0
Name: price, dtype: float64

In [ ]:
#Finance department wants to know the least expensive shoe for each shoe_type (i.e., the most expensive boot, the most expensive ballet flat, etc.).
#But this time convert the series into a dataframe and rename the columns as well

least_pricey_shoe = orders.groupby('shoe_type').price.min().reset_index() #The reset index converts the series into a dataframe
least_pricey_shoe

      shoe_type  price
0  ballet flats   91.0
1         boots  100.0
2         clogs   93.0
3       sandals  113.0
4     stilettos  167.0
5        wedges  115.0

In [ ]:
least_pricey_shoe.rename(columns={
    "price" : "Min Price"
},inplace=True)
least_pricey_shoe

      shoe_type  Min Price
0  ballet flats       91.0
1         boots      100.0
2         clogs       93.0
3       sandals      113.0
4     stilettos      167.0
5        wedges      115.0

In [ ]:
#Once more, we’ll return to the data from ShoeFly.com. Our Marketing team says that it’s important to have some affordably priced shoes available for every color of shoe that we sell.
#Let’s calculate the 25th percentile for shoe price for each shoe_color to help Marketing decide if we have enough cheap shoes on sale. Save the data to the variable cheap_shoes.

import numpy as np

cheap_shoes = orders.groupby('shoe_color').price.apply(lambda x: np.percentile(x,25)).reset_index()
cheap_shoes

  shoe_color  price
0      black    NaN
1      brown  193.5
2       navy  205.5
3        red  250.0
4      white  196.0

In [ ]:
#.At ShoeFly.com, our Purchasing team thinks that certain shoe_type/shoe_color combinations are particularly popular this year (for example, blue ballet flats are all the rage in Paris).
# Create a DataFrame with the total number of shoes of each shoe_type/shoe_color combination purchased. Save it to the variable shoe_counts.

shoe_counts = orders.groupby(['shoe_type','shoe_color']).id.count().reset_index()
print(shoe_counts)

       shoe_type shoe_color  id
0   ballet flats      black   2
1   ballet flats      brown   5
2   ballet flats        red   3
3   ballet flats      white   5
4          boots      black   3
5          boots      brown   5
6          boots       navy   6
7          boots        red   2
8          boots      white   3
9          clogs      black   4
10         clogs      brown   6
11         clogs       navy   1
12         clogs        red   4
13         clogs      white   1
14       sandals      black   1
15       sandals      brown   4
16       sandals       navy   5
17       sandals        red   3
18       sandals      white   4
19     stilettos      black   5
20     stilettos      brown   3
21     stilettos       navy   2
22     stilettos        red   2
23     stilettos      white   2
24        wedges      black   3
25        wedges      brown   4
26        wedges       navy   4
27        wedges        red   5
28        wedges      white   2

In [ ]:
# What if we want to do a pivot for a better analysis
# Syntax is: df.pivot(columns='ColumnToPivot',
#             index='ColumnToBeRows',
#             values='ColumnToBeValues')

# The Sales Manager has asked us to pivot the dataframe

shoe_counts_pivot = shoe_counts.pivot(
    columns = 'shoe_color',
    index = 'shoe_type',
    values = 'id'
).reset_index()
shoe_counts_pivot

shoe_color     shoe_type  black  brown  navy  red  white
0           ballet flats    2.0    5.0   NaN  3.0    5.0
1                  boots    3.0    5.0   6.0  2.0    3.0
2                  clogs    4.0    6.0   1.0  4.0    1.0
3                sandals    1.0    4.0   5.0  3.0    4.0
4              stilettos    5.0    3.0   2.0  2.0    2.0
5                 wedges    3.0    4.0   4.0  5.0    2.0

# **Pratice Coding for the Aggreagration Exercise**

In [ ]:
user_visits = pd.read_csv('page_visits.csv')

print(user_visits.head())

#The column utm_source contains information about how users got to ShoeFly’s homepage. For instance, if utm_source = Facebook, then the user came to ShoeFly by clicking on an ad on Facebook.com.
# Use a groupby statement to calculate how many visits came from each of the different sources. Save your answer to the variable click_source.

click_source = user_visits.groupby('utm_source').id.count().reset_index()
print(click_source)

#Our Marketing department thinks that the traffic to our site has been changing over the past few months. Use groupby to calculate the number of visits to our site from each utm_source for each month. Save your answer to the variable click_source_by_month.

click_source_by_month = user_visits.groupby(['utm_source','month']).id.count().reset_index()

#The head of Marketing is complaining that this table is hard to read. Use pivot to create a pivot table where the rows are utm_source and the columns are month. Save your results to the variable click_source_by_month_pivot.

click_source_by_month_pivot = click_source_by_month.pivot(
  columns = 'month',
  index = 'utm_source',
  values = 'id'
).reset_index()

print(click_source_by_month_pivot)

      id first_name last_name                       email         month  \
0  10043      Louis      Koch       LouisKoch43@gmail.com     3 - March
1  10150      Bruce      Webb     BruceWebb44@outlook.com     3 - March
2  10155   Nicholas   Hoffman  Nicholas.Hoffman@gmail.com  2 - February
3  10178    William       Key     William.Key@outlook.com     3 - March
4  10208      Karen      Bass            KB4971@gmail.com  2 - February

  utm_source
0      yahoo
1    twitter
2     google
3      yahoo
4     google
  utm_source   id
0      email  462
1   facebook  823
2     google  543
3    twitter  415
4      yahoo  757
month utm_source  1 - January  2 - February  3 - March
0          email           43           147        272
1       facebook          404           263        156
2         google          127           196        220
3        twitter          164           154         97
4          yahoo          262           240        255

# **Project on Aggregates:**

A/B Testing for ShoeFly.com
Our favorite online shoe store, ShoeFly.com is performing an A/B Test. They have two different versions of an ad, which they have placed in emails, as well as in banner ads on Facebook, Twitter, and Google. They want to know how the two ads are performing on each of the different platforms on each day of the week. Help them analyze the data using aggregate measures.

In [ ]:
ad_clicks = pd.read_csv('ad_clicks.csv')

#Examine the first few rows of ad_clicks.
print(ad_clicks.head())

#Your manager wants to know which ad platform is getting you the most views.
#How many views (i.e., rows of the table) came from each utm_source?

views_from_each_source = ad_clicks.groupby('utm_source').user_id.count().reset_index()
print(views_from_each_source)

#Below line is written to verify if all the sources are covered
print(ad_clicks['utm_source'].unique())

#If the column ad_click_timestamp is not null, then someone actually clicked on the ad that was displayed.
# Create a new column called is_click, which is True if ad_click_timestamp is not null and False otherwise.

ad_clicks['is_click'] = ad_clicks.ad_click_timestamp.notnull()

#We want to know the percent of people who clicked on ads from each utm_source.
#Start by grouping by utm_source and is_click and counting the number of user_id‘s in each of those groups. Save your answer to the variable clicks_by_source.

clicks_by_source = ad_clicks.groupby(['utm_source','is_click']).user_id.count().reset_index()

#Now let’s pivot the data so that the columns are is_click (either True or False), the index is utm_source, and the values are user_id.Save your results to the variable clicks_pivot.

clicks_pivot = clicks_by_source.pivot(
  columns = 'is_click',
  index = 'utm_source',
  values = 'user_id'
).reset_index()

#Create a new column in clicks_pivot called percent_clicked which is equal to the percent of users who clicked on the ad from each utm_source.Was there a difference in click rates for each source?

clicks_pivot['percent_clicked'] = \
   clicks_pivot[True] / \
   (clicks_pivot[True] +
    clicks_pivot[False])

print(clicks_pivot)

#The column experimental_group tells us whether the user was shown Ad A or Ad B. Were approximately the same number of people shown both ads?

experimental_group_count = ad_clicks.groupby('experimental_group').user_id.count().reset_index()
print(experimental_group_count)

#Using the column is_click that we defined earlier, check to see if a greater percentage of users clicked on Ad A or Ad B.

user_ad_click_count = ad_clicks.groupby(['experimental_group','is_click']).user_id.count().reset_index()
user_ad_click_count_pivot = user_ad_click_count.pivot(
  columns = 'is_click',
  index = 'experimental_group',
  values = 'user_id'
).reset_index()
print(user_ad_click_count_pivot)

#The Product Manager for the A/B test thinks that the clicks might have changed by day of the week.
#Start by creating two DataFrames: a_clicks and b_clicks, which contain only the results for A group and B group, respectively.

a_clicks = ad_clicks[ad_clicks['experimental_group'] == 'A']
b_clicks = ad_clicks[ad_clicks['experimental_group'] == 'B']

print(a_clicks.head())
print(b_clicks.head())

#For each group (a_clicks and b_clicks), calculate the percent of users who clicked on the ad by day.

a_clicks_percent = a_clicks.groupby(['is_click','day']).user_id.count().reset_index()
a_clicks_percent_pivot = a_clicks_percent.pivot(
  columns = 'day',
  index = 'is_click',
  values = 'user_id'
).reset_index()
print(a_clicks_percent_pivot)

b_clicks_percent = b_clicks.groupby(['is_click','day']).user_id.count().reset_index()
b_clicks_percent_pivot = b_clicks_percent.pivot(
  columns = 'day',
  index = 'is_click',
  values = 'user_id'
).reset_index()
print(b_clicks_percent_pivot)

                                user_id utm_source           day  \
0  008b7c6c-7272-471e-b90e-930d548bd8d7     google  6 - Saturday
1  009abb94-5e14-4b6c-bb1c-4f4df7aa7557   facebook    7 - Sunday
2  00f5d532-ed58-4570-b6d2-768df5f41aed    twitter   2 - Tuesday
3  011adc64-0f44-4fd9-a0bb-f1506d2ad439     google   2 - Tuesday
4  012137e6-7ae7-4649-af68-205b4702169c   facebook    7 - Sunday

  ad_click_timestamp experimental_group
0               7:18                  A
1                NaN                  B
2                NaN                  A
3                NaN                  B
4                NaN                  B
  utm_source  user_id
0      email      255
1   facebook      504
2     google      680
3    twitter      215
['google' 'facebook' 'twitter' 'email']
is_click utm_source  False  True  percent_clicked
0             email    175    80         0.313725
1          facebook    324   180         0.357143
2            google    441   239         0.351471
3           twitter    149    66         0.306977
  experimental_group  user_id
0                  A      827
1                  B      827
is_click experimental_group  False  True
0                         A    517   310
1                         B    572   255
                                user_id utm_source            day  \
0  008b7c6c-7272-471e-b90e-930d548bd8d7     google   6 - Saturday
2  00f5d532-ed58-4570-b6d2-768df5f41aed    twitter    2 - Tuesday
5  013b0072-7b72-40e7-b698-98b4d0c9967f   facebook     1 - Monday
6  0153d85b-7660-4c39-92eb-1e1acd023280     google   4 - Thursday
7  01555297-d6e6-49ae-aeba-1b196fdbb09f     google  3 - Wednesday

  ad_click_timestamp experimental_group  is_click
0               7:18                  A      True
2                NaN                  A     False
5                NaN                  A     False
6                NaN                  A     False
7                NaN                  A     False
                                 user_id utm_source            day  \
1   009abb94-5e14-4b6c-bb1c-4f4df7aa7557   facebook     7 - Sunday
3   011adc64-0f44-4fd9-a0bb-f1506d2ad439     google    2 - Tuesday
4   012137e6-7ae7-4649-af68-205b4702169c   facebook     7 - Sunday
9   01a210c3-fde0-4e6f-8efd-4f0e38730ae6      email    2 - Tuesday
10  01adb2e7-f711-4ae4-a7c6-29f48457eea1     google  3 - Wednesday

   ad_click_timestamp experimental_group  is_click
1                 NaN                  B     False
3                 NaN                  B     False
4                 NaN                  B     False
9               15:21                  B      True
10                NaN                  B     False
day  is_click  1 - Monday  2 - Tuesday  3 - Wednesday  4 - Thursday  \
0       False          70           76             86            69
1        True          43           43             38            47

day  5 - Friday  6 - Saturday  7 - Sunday
0            77            73          66
1            51            45          43
day  is_click  1 - Monday  2 - Tuesday  3 - Wednesday  4 - Thursday  \
0       False          81           74             89            87
1        True          32           45             35            29

day  5 - Friday  6 - Saturday  7 - Sunday
0            90            76          75
1            38            42          34

# **Working with Multiple DataFrames**

In [ ]:
#The pandas .merge() method looks for columns that are common between two DataFrames and then looks for rows
#where those column's value are the same. It then combines the matching rows into a single row in a new table

#new_df = pd.merge(df1, df2)

In [ ]:
'''
You are an analyst at Cool T-Shirts Inc. You are going to help them analyze some of their sales data.

There are two DataFrames defined in the file script.py:

sales contains the monthly revenue for Cool T-Shirts Inc. It has two columns: month and revenue.
targets contains the goals for monthly revenue for each month. It has two columns: month and target.
Create a new DataFrame sales_vs_targets which contains the merge of sales and targets.
'''

sales  = pd.read_csv('sales.csv')
targets = pd.read_csv('targets.csv')

sales_vs_targets = pd.merge(sales,targets)
sales_vs_targets #Both Dataframes had month as the common column

      month  revenue  target
0   January      300     310
1  February      290     270
2     March      310     300
3     April      325     350
4       May      475     475
5      June      495     500

In [ ]:
#Cool T-Shirts Inc. wants to know the months when they crushed their targets.
#Select the rows from sales_vs_targets where revenue is greater than target. Save these rows to the variable crushing_it.

crushing_it = sales_vs_targets[(sales_vs_targets['revenue']) > (sales_vs_targets['target'])]
print(crushing_it)

      month  revenue  target
1  February      290     270
2     March      310     300

In [ ]:
#We can also use chaining of merge when we want to have multiple DFs to be merged

#We have some more data from Cool T-Shirts Inc. The number of men’s and women’s t-shirts sold
#per month is in a file called men_women_sales.csv. Load this data into a DataFrame called men_women.

men_women = pd.read_csv('men_women_sales.csv')
men_women

      month  men  women
0   January   30     35
1  February   29     35
2     March   31     29
3     April   32     28
4       May   47     50
5      June   49     45

In [ ]:
all_data = sales.merge(targets).merge(men_women)
all_data

      month  revenue  target  men  women
0   January      300     310   30     35
1  February      290     270   29     35
2     March      310     300   31     29
3     April      325     350   32     28
4       May      475     475   47     50
5      June      495     500   49     45

In [ ]:
'''
  Select the rows of all_data where:
    revenue is greater than target
      AND
    women is greater than men
  Save your answer to the variable results.
'''

results = all_data[(all_data['revenue'] > all_data['target']) & (all_data['women'] > all_data['men'])]
print(results)

      month  revenue  target  men  women
1  February      290     270   29     35

In [ ]:
#Now lets imagine if we have two tables with no common Columns except for ID.
#When we would do a merge it would create bad data.So we use the below

orders_merge = pd.read_csv('orders_merge.csv')
print(orders_merge)
products_merge = pd.read_csv('products_merge.csv')
print(products_merge)

   id  product_id  customer_id  quantity   timestamp
0   1           3            2         1  2017-01-01
1   2           2            2         3  2017-01-01
2   3           1            3         1  2017-01-01
3   4           2            3         2  2016-02-01
4   5           3            3         3  2017-02-01
5   6           4            1         2  2017-03-01
6   7           1            1         1  2017-02-02
7   8           4            1         1  2017-02-02
   id         description  price
0   1      thing-a-ma-jig      5
1   2  whatcha-ma-call-it     10
2   3          doo-hickey      7
3   4               gizmo      3

In [ ]:
orders_products = pd.merge(orders_merge, products_merge.rename(columns={'id' : 'product_id'}))
orders_products

,id,product_id,customer_id,quantity,timestamp,description,price
0,1,3,2,1,2017-01-01,doo-hickey,7
1,2,2,2,3,2017-01-01,whatcha-ma-call-it,10
2,3,1,3,1,2017-01-01,thing-a-ma-jig,5
3,4,2,3,2,2016-02-01,whatcha-ma-call-it,10
4,5,3,3,3,2017-02-01,doo-hickey,7
5,6,4,1,2,2017-03-01,gizmo,3
6,7,1,1,1,2017-02-02,thing-a-ma-jig,5
7,8,4,1,1,2017-02-02,gizmo,3

In [ ]:
'''
If we don’t want to do that, we have another option. We could use the keywords left_on and right_on to specify
which columns we want to perform the merge on. In the example below, the “left” table is the one that comes
first (orders), and the “right” table is the one that comes second (customers).
This syntax says that we should match the customer_id from orders to the id in customers.

Syntax:

pd.merge(
    orders,
    customers,
    left_on='customer_id',
    right_on='id',
    suffixes=['_order', '_customer']
)
'''

orders_products = pd.merge(orders_merge,
                           products_merge,
                           left_on='product_id',
                           right_on='id',
                           suffixes=['_order','_products'])
orders_products

,id_order,product_id,customer_id,quantity,timestamp,id_products,description,price
0,1,3,2,1,2017-01-01,3,doo-hickey,7
1,2,2,2,3,2017-01-01,2,whatcha-ma-call-it,10
2,3,1,3,1,2017-01-01,1,thing-a-ma-jig,5
3,4,2,3,2,2016-02-01,2,whatcha-ma-call-it,10
4,5,3,3,3,2017-02-01,3,doo-hickey,7
5,6,4,1,2,2017-03-01,4,gizmo,3
6,7,1,1,1,2017-02-02,1,thing-a-ma-jig,5
7,8,4,1,1,2017-02-02,4,gizmo,3

In [ ]:
#So all the examples we did until now is for the INNER MERGE, it is like an intersection
#So if there is no commanlity between two tables for some rows, those rows would not be VISIBLE
#in the new merged DF

#Hence the new concept of OUTER MERGE

'''
There are two hardware stores in town: Store A and Store B. Store A’s inventory
is in DataFrame store_a and Store B’s inventory is in DataFrame store_b.
They have decided to merge into one big Super Store! We need to merge their data
'''

store_a = pd.read_csv('store_a.csv')
store_b = pd.read_csv('store_b.csv')

store_a_b_outer = pd.merge(store_a,store_b,how='outer')
store_a_b_outer

             item  store_a_inventory  store_b_inventory
0       duct tape              150.0              150.0
1          hammer               12.0                6.0
2           nails              200.0              250.0
3        pvc pipe               54.0               54.0
4            rake                NaN               10.0
5             saw                6.0                6.0
6     screwdriver               15.0                NaN
7          screws              350.0                NaN
8          shovel                NaN               15.0
9   wooden dowels                NaN              192.0
10         wrench               12.0                NaN

In [ ]:
#Same goes for different merges, if we want to keep all the information for store A
#and keep the intersecting information from store B, discarding the information from
#store B which does not common grounds in store A, we user LEFT MERGE and RIGHT MERGE
#if vice versa

store_a_b_left = pd.merge(store_a,store_b,how='left')
store_a_b_left

          item  store_a_inventory  store_b_inventory
0       hammer                 12                6.0
1  screwdriver                 15                NaN
2        nails                200              250.0
3       screws                350                NaN
4          saw                  6                6.0
5    duct tape                150              150.0
6       wrench                 12                NaN
7     pvc pipe                 54               54.0

In [ ]:
store_b_a_left = pd.merge(store_a,store_b,how='right')
store_b_a_left

            item  store_a_inventory  store_b_inventory
0         hammer               12.0                  6
1          nails              200.0                250
2            saw                6.0                  6
3      duct tape              150.0                150
4       pvc pipe               54.0                 54
5           rake                NaN                 10
6         shovel                NaN                 15
7  wooden dowels                NaN                192

In [61]:
#When we have a dataframe which is split into multiple smaller DFs,
#We can use the concat function
#pd.concat([df1, df2])

**Mini Review**

In [63]:
import pandas as pd

visits = pd.read_csv('visits.csv',
                        parse_dates=[1])
checkouts = pd.read_csv('checkouts.csv',
                        parse_dates=[1])

'''
.
Cool T-Shirts Inc. just created a website for ordering their products. They want you to analyze two datasets for them:

visits contains information on all visits to their landing page
checkouts contains all users who began to checkout on their website
'''
print(visits)
print(checkouts)

'''
We want to know the amount of time from a user\’s initial visit to the website to when they start to check out.

Use merge to combine visits and checkouts and save it to the variable v_to_c.
'''
v_to_c = pd.merge(visits, checkouts,how='inner')
print(v_to_c)

'''
In order to calculate the time between visiting and checking out, define a column of v_to_c called time that calculates the difference between checkout_time and visit_time for every row.
'''

v_to_c['time'] = v_to_c['checkout_time'] - v_to_c['visit_time']
print(v_to_c)

#Use .mean() to calculate the average time to checkout and print that value to the terminal.
print(v_to_c['time'].mean())

                                 user_id          visit_time
0   319350b4-9951-47ef-b3a7-6b252099905f 2017-02-21 07:16:00
1   7435ec9f-576d-4ebd-8791-361b128fca77 2017-05-16 08:37:00
2   0b061e73-f709-42fa-8d1a-5f68176ff154 2017-04-12 19:32:00
3   9133d6f0-e68b-4c8d-bafd-ff2825e8dafe 2017-08-18 04:32:00
4   08d13edb-071c-4cfb-9ee4-8f377d0e932a 2017-07-08 06:24:00
..                                   ...                 ...
95  442efd1c-8d7b-4d6a-83be-8f2a9e08b34f 2017-02-19 11:20:00
96  5679519b-a901-4970-8656-dbf60ffb618d 2017-07-20 04:23:00
97  26deb2d5-1d7e-4774-bf6e-1df2ee9ee59d 2017-09-06 07:29:00
98  fff8f87a-e4a2-4f2c-b3d4-93a4ece95c4f 2017-06-06 23:42:00
99  42617776-2850-431d-9262-a9c11e5ad17f 2017-02-10 10:49:00

[100 rows x 2 columns]
                                 user_id       checkout_time
0   fe90a9f4-960a-4a0d-9160-e562adb79365 2017-11-09 09:25:00
1   1a35b7eb-f603-407d-91be-a2c3304066fd 2017-08-15 21:25:00
2   e2c24ee0-7fdf-4400-abde-b36378fe5ce6 2017-07-04 15:39:00
3   10dbd3c5-d610-44e9-9994-110a7950b6b4 2017-08-09 21:07:00
4   f028e9dd-77d0-4002-83f6-372a4837fda6 2017-10-27 08:57:00
..                                   ...                 ...
75  7fe800cc-46e8-427c-a7af-f27198d305a1 2017-01-18 13:14:00
76  43db76fc-d522-450d-a371-ef2a683d5bfd 2017-03-26 21:31:00
77  851b52d1-31e9-468d-834f-5363fee108ac 2017-09-21 22:24:00
78  7435ec9f-576d-4ebd-8791-361b128fca77 2017-05-16 08:55:00
79  319350b4-9951-47ef-b3a7-6b252099905f 2017-02-21 07:40:00

[80 rows x 2 columns]
                                 user_id          visit_time  \
0   319350b4-9951-47ef-b3a7-6b252099905f 2017-02-21 07:16:00
1   319350b4-9951-47ef-b3a7-6b252099905f 2017-02-21 07:16:00
2   7435ec9f-576d-4ebd-8791-361b128fca77 2017-05-16 08:37:00
3   7435ec9f-576d-4ebd-8791-361b128fca77 2017-05-16 08:37:00
4   08d13edb-071c-4cfb-9ee4-8f377d0e932a 2017-07-08 06:24:00
..                                   ...                 ...
75  23a8d1be-3f5c-4b59-aed7-c7f19c51612b 2017-08-11 13:49:00
76  8d9ac96c-16be-418e-8df4-1a6202d0b36e 2017-10-07 10:23:00
77  8d9ac96c-16be-418e-8df4-1a6202d0b36e 2017-10-07 10:23:00
78  5679519b-a901-4970-8656-dbf60ffb618d 2017-07-20 04:23:00
79  fff8f87a-e4a2-4f2c-b3d4-93a4ece95c4f 2017-06-06 23:42:00

         checkout_time
0  2017-02-21 07:27:00
1  2017-02-21 07:40:00
2  2017-05-16 08:49:00
3  2017-05-16 08:55:00
4  2017-07-08 06:32:00
..                 ...
75 2017-08-11 14:11:00
76 2017-10-07 10:24:00
77 2017-10-07 10:52:00
78 2017-07-20 04:24:00
79 2017-06-07 00:11:00

[80 rows x 3 columns]
                                 user_id          visit_time  \
0   319350b4-9951-47ef-b3a7-6b252099905f 2017-02-21 07:16:00
1   319350b4-9951-47ef-b3a7-6b252099905f 2017-02-21 07:16:00
2   7435ec9f-576d-4ebd-8791-361b128fca77 2017-05-16 08:37:00
3   7435ec9f-576d-4ebd-8791-361b128fca77 2017-05-16 08:37:00
4   08d13edb-071c-4cfb-9ee4-8f377d0e932a 2017-07-08 06:24:00
..                                   ...                 ...
75  23a8d1be-3f5c-4b59-aed7-c7f19c51612b 2017-08-11 13:49:00
76  8d9ac96c-16be-418e-8df4-1a6202d0b36e 2017-10-07 10:23:00
77  8d9ac96c-16be-418e-8df4-1a6202d0b36e 2017-10-07 10:23:00
78  5679519b-a901-4970-8656-dbf60ffb618d 2017-07-20 04:23:00
79  fff8f87a-e4a2-4f2c-b3d4-93a4ece95c4f 2017-06-06 23:42:00

         checkout_time            time
0  2017-02-21 07:27:00 0 days 00:11:00
1  2017-02-21 07:40:00 0 days 00:24:00
2  2017-05-16 08:49:00 0 days 00:12:00
3  2017-05-16 08:55:00 0 days 00:18:00
4  2017-07-08 06:32:00 0 days 00:08:00
..                 ...             ...
75 2017-08-11 14:11:00 0 days 00:22:00
76 2017-10-07 10:24:00 0 days 00:01:00
77 2017-10-07 10:52:00 0 days 00:29:00
78 2017-07-20 04:24:00 0 days 00:01:00
79 2017-06-07 00:11:00 0 days 00:29:00

[80 rows x 4 columns]
0 days 00:15:24.750000

# **Final Project**

Cool T-Shirts Inc. has asked you to analyze data on visits to their website. Your job is to build a funnel, which is a description of how many people continue to the next step of a multi-step process.

In this case, our funnel is going to describe the following process:

1. A user visits CoolTShirts.com
2. A user adds a t-shirt to their cart
3. A user clicks “checkout”
4. A user actually purchases a t-shirt

In [64]:
import pandas as pd

visits = pd.read_csv('visits_project.csv',
                     parse_dates=[1])
cart = pd.read_csv('cart.csv',
                   parse_dates=[1])
checkout = pd.read_csv('checkout.csv',
                       parse_dates=[1])
purchase = pd.read_csv('purchase.csv',
                       parse_dates=[1])

#Step 1: Inspect the DataFrames using print and head:
print(visits.head())
print(cart.head())
print(checkout.head())
print(purchase.head())

#Step 2: Combine visits and cart using a left merge.
visits_cart = pd.merge(visits,cart,how='left')
print(visits_cart.head())
#Step 3: How long is your merged DataFrame?
total_visits = len(visits_cart)
print(total_visits)

#Step 4: How many of the timestamps are null for the column cart_time? What do these null rows mean?
didnt_reach_cart = len(visits_cart[visits_cart['cart_time'].isnull()])
print(didnt_reach_cart)
#Step 5: What percent of users who visited Cool T-Shirts Inc. ended up not placing a t-shirt in their cart?
no_order_placed = float(didnt_reach_cart)/float(total_visits)
print(no_order_placed)

#Step 6: Repeat the left merge for cart and checkout and count null values. What percentage of users put items in their cart, but did not proceed to checkout?

cart_checkout = pd.merge(cart,checkout,how='left')
total_carts_created = len(cart_checkout)
didnt_reach_checkout = len(cart_checkout[cart_checkout['checkout_time'].isnull()])

print(total_carts_created)
print(didnt_reach_checkout)
total_no_checkout = float(didnt_reach_checkout)/float(total_carts_created)
print(total_no_checkout)

#Step 7: Merge all four steps of the funnel, in order, using a series of left merges. Save the results to the variable all_data.

all_data = visits.merge(cart,how='left').merge(checkout,how='left').merge(purchase,how='left')
print(all_data.head())

#Step 8: What percentage of users proceeded to checkout, but did not purchase a t-shirt?
reached_checkout = all_data[~all_data['checkout_time'].isnull()]
didnt_purchase = all_data[(all_data['purchase_time'].isnull()) & (~all_data['checkout_time'].isnull())]
checked_out_didnt_purchase = float(len(didnt_purchase))/float(len(reached_checkout))
print("% of users who got to checkout but did not purchase:",checked_out_didnt_purchase)

#Step 9: Which step of the funnel is weakest (i.e., has the highest percentage of users not completing it)? How might Cool T-Shirts Inc. change their website to fix this problem?
print("{} percent of users who visited the page did not add a t-shirt to their cart".format(round(no_order_placed*100, 2)))
print("{} percent of users who added a t-shirt to their cart did not checkout".format(round(total_no_checkout*100, 2)))
print("{} percent of users who made it to checkout  did not purchase a shirt".format(round( checked_out_didnt_purchase*100, 2)))

#Step 10: Using the giant merged DataFrame all_data that you created, let’s calculate the average time from initial visit to final purchase. Add a column that is the difference between purchase_time and visit_time.

all_data['total_time'] = all_data['purchase_time'] - all_data['visit_time']
print(all_data.head())

#Step 11: Examine the results by printing the new column to the screen.
print(all_data['total_time'])

#Step 12: Calculate the average time to purchase by applying the .mean() function to your new column.
print(all_data['total_time'].mean())

                                user_id          visit_time
0  943647ef-3682-4750-a2e1-918ba6f16188 2017-04-07 15:14:00
1  0c3a3dd0-fb64-4eac-bf84-ba069ce409f2 2017-01-26 14:24:00
2  6e0b2d60-4027-4d9a-babd-0e7d40859fb1 2017-08-20 08:23:00
3  6879527e-c5a6-4d14-b2da-50b85212b0ab 2017-11-04 18:15:00
4  a84327ff-5daa-4ba1-b789-d5b4caf81e96 2017-02-27 11:25:00
                                user_id           cart_time
0  2be90e7c-9cca-44e0-bcc5-124b945ff168 2017-11-07 20:45:00
1  4397f73f-1da3-4ab3-91af-762792e25973 2017-05-27 01:35:00
2  a9db3d4b-0a0a-4398-a55a-ebb2c7adf663 2017-03-04 10:38:00
3  b594862a-36c5-47d5-b818-6e9512b939b3 2017-09-27 08:22:00
4  a68a16e2-94f0-4ce8-8ce3-784af0bbb974 2017-07-26 15:48:00
                                user_id       checkout_time
0  d33bdc47-4afa-45bc-b4e4-dbe948e34c0d 2017-06-25 09:29:00
1  4ac186f0-9954-4fea-8a27-c081e428e34e 2017-04-07 20:11:00
2  3c9c78a7-124a-4b77-8d2e-e1926e011e7d 2017-07-13 11:38:00
3  89fe330a-8966-4756-8f7c-3bdbcd47279a 2017-04-20 16:15:00
4  3ccdaf69-2d30-40de-b083-51372881aedd 2017-01-08 20:52:00
                                user_id       purchase_time
0  4b44ace4-2721-47a0-b24b-15fbfa2abf85 2017-05-11 04:25:00
1  02e684ae-a448-408f-a9ff-dcb4a5c99aac 2017-09-05 08:45:00
2  4b4bc391-749e-4b90-ab8f-4f6e3c84d6dc 2017-11-20 20:49:00
3  a5dbb25f-3c36-4103-9030-9f7c6241cd8d 2017-01-22 15:18:00
4  46a3186d-7f5a-4ab9-87af-84d05bfd4867 2017-06-11 11:32:00
                                user_id          visit_time  \
0  943647ef-3682-4750-a2e1-918ba6f16188 2017-04-07 15:14:00
1  0c3a3dd0-fb64-4eac-bf84-ba069ce409f2 2017-01-26 14:24:00
2  6e0b2d60-4027-4d9a-babd-0e7d40859fb1 2017-08-20 08:23:00
3  6879527e-c5a6-4d14-b2da-50b85212b0ab 2017-11-04 18:15:00
4  a84327ff-5daa-4ba1-b789-d5b4caf81e96 2017-02-27 11:25:00

            cart_time
0                 NaT
1 2017-01-26 14:44:00
2 2017-08-20 08:31:00
3                 NaT
4                 NaT
2000
1652
0.826
482
122
0.25311203319502074
                                user_id          visit_time  \
0  943647ef-3682-4750-a2e1-918ba6f16188 2017-04-07 15:14:00
1  0c3a3dd0-fb64-4eac-bf84-ba069ce409f2 2017-01-26 14:24:00
2  6e0b2d60-4027-4d9a-babd-0e7d40859fb1 2017-08-20 08:23:00
3  6879527e-c5a6-4d14-b2da-50b85212b0ab 2017-11-04 18:15:00
4  a84327ff-5daa-4ba1-b789-d5b4caf81e96 2017-02-27 11:25:00

            cart_time       checkout_time       purchase_time
0                 NaT                 NaT                 NaT
1 2017-01-26 14:44:00 2017-01-26 14:54:00 2017-01-26 15:08:00
2 2017-08-20 08:31:00                 NaT                 NaT
3                 NaT                 NaT                 NaT
4                 NaT                 NaT                 NaT
% of users who got to checkout but did not purchase: 0.1688963210702341
82.6 percent of users who visited the page did not add a t-shirt to their cart
25.31 percent of users who added a t-shirt to their cart did not checkout
16.89 percent of users who made it to checkout  did not purchase a shirt
                                user_id          visit_time  \
0  943647ef-3682-4750-a2e1-918ba6f16188 2017-04-07 15:14:00
1  0c3a3dd0-fb64-4eac-bf84-ba069ce409f2 2017-01-26 14:24:00
2  6e0b2d60-4027-4d9a-babd-0e7d40859fb1 2017-08-20 08:23:00
3  6879527e-c5a6-4d14-b2da-50b85212b0ab 2017-11-04 18:15:00
4  a84327ff-5daa-4ba1-b789-d5b4caf81e96 2017-02-27 11:25:00

            cart_time       checkout_time       purchase_time      total_time
0                 NaT                 NaT                 NaT             NaT
1 2017-01-26 14:44:00 2017-01-26 14:54:00 2017-01-26 15:08:00 0 days 00:44:00
2 2017-08-20 08:31:00                 NaT                 NaT             NaT
3                 NaT                 NaT                 NaT             NaT
4                 NaT                 NaT                 NaT             NaT
0                  NaT
1      0 days 00:44:00
2                  NaT
3                  NaT
4                  NaT
             ...
2367               NaT
2368               NaT
2369               NaT
2370               NaT
2371               NaT
Name: total_time, Length: 2372, dtype: timedelta64[ns]
0 days 00:43:53.360160965